### ISSUE TITLE
Firing trigger/moving to state inside OnEntry deadlocks

### ISSUE THREAD

**Issue by oysteinkrog** [prasannavl/LiquidState#27]
The OnEntry handler for TestState.C is never called.
```
        public enum TestState
        {
            A, 
            B,
            C
        }

        public enum TestTrigger
        {
            TriggA,
            TriggB,
            TriggC
        }

        [Test]
        public async Task Test()
        {
            QueuedAwaitableStateMachine<TestState, TestTrigger> stateMachine = null;
            AwaitableConfiguration<TestState, TestTrigger> config = StateMachineFactory.CreateAwaitableConfiguration<TestState, TestTrigger>();

            config.ForState(TestState.A)
                .OnEntry(async () =>
                {
                    await stateMachine.FireAsync(TestTrigger.TriggB);
                })
                .Permit(TestTrigger.TriggB, TestState.B);

            config.ForState(TestState.B)
                .OnEntry(async () =>
                {
                    await stateMachine.FireAsync(TestTrigger.TriggC);
                })
                .Permit(TestTrigger.TriggA, TestState.A)
                .Permit(TestTrigger.TriggC, TestState.C);

            config.ForState(TestState.C)
                .OnEntry(async () =>
                {
                })
                .Permit(TestTrigger.TriggB, TestState.B)
                .Permit(TestTrigger.TriggA, TestState.A);

            stateMachine = new QueuedAwaitableStateMachine<TestState, TestTrigger>(TestState.A, config);

            Assert.AreEqual(TestState.A, stateMachine.CurrentState);
            await stateMachine.FireAsync(TestTrigger.TriggB);
            Assert.AreEqual(TestState.B, stateMachine.CurrentState);
        }

```

**Comment by oysteinkrog** [comment]
Seems to be because the locking/monitors in QueuedAwaitableStateMachineBase does not support this scenario.
StartQueueIfNecessaryAsync() is called on the nested transition/trigger but never actually processes the queued actions.

**Comment by oysteinkrog** [comment]
One idea I had was to track the async context such that when we enter the nested FireAsync() we can actually process the queue.The InterlockedMonitor is entered but we don't know that it is "us" that did it.
I tried some async primitives from AsyncEx but could not get it working.
The I tried AsyncLocal<bool> from .net 4.6, to simply keep track of whether the monitor is entered or not, and then checking that in StartQueueIfNecessaryAsync().
This works, but I have no idea if it's correct...

'''
// Author: Prasanna V. Loganathar
// Created: 09:55 16-07-2015
// Project: LiquidState
// License: http://www.apache.org/licenses/LICENSE-2.0

using System;
using System.Collections.Immutable;
using System.Threading;
using System.Threading.Tasks;
using LiquidState.Awaitable.Core;
using LiquidState.Common;
using LiquidState.Core;

namespace LiquidState.Awaitable
{
    public abstract class NestedQueuedAwaitableStateMachineBase_<TState, TTrigger> :
        RawAwaitableStateMachineBase<TState, TTrigger>
    {
        private IImmutableQueue<Func<Task>> actionsQueue;
        private int queueCount;
        private InterlockedBlockingMonitor queueMonitor = new InterlockedBlockingMonitor();
        private InterlockedMonitor monitor = new InterlockedMonitor();
        private AsyncLocal<bool> asyncMonitor = new AsyncLocal<bool>();

        protected NestedQueuedAwaitableStateMachineBase_(TState initialState, AwaitableConfiguration<TState, TTrigger> config)
            : base(initialState, config)
        {
            actionsQueue = ImmutableQueue.Create<Func<Task>>();
        }

        public override async Task MoveToStateAsync(TState state,
            StateTransitionOption option = StateTransitionOption.Default)
        {
            var flag = true;

            queueMonitor.Enter();
            if (monitor.TryEnter())
            {
                asyncMonitor.Value = true;

                if (queueCount == 0)
                {
                    queueMonitor.Exit();
                    flag = false;

                    try
                    {
                        await base.MoveToStateAsync(state, option);
                    }
                    finally
                    {
                        queueMonitor.Enter();
                        if (queueCount > 0)
                        {
                            queueMonitor.Exit();
                            var _ = StartQueueIfNecessaryAsync(true);
                            // Should not exit monitor here. Its handled by the process queue.
                        }
                        else
                        {
                            queueMonitor.Exit();
                            asyncMonitor.Value = false;
                        }
                    }
                }
            }

            if (flag)
            {
                var tcs = new TaskCompletionSource<bool>();

                actionsQueue = actionsQueue.Enqueue(async () =>
                {
                    try
                    {
                        await base.MoveToStateAsync(state, option);
                        tcs.TrySetResult(true);
                    }
                    catch (Exception ex)
                    {
                        tcs.SetException(ex);
                    }
                });

                queueCount++;
                queueMonitor.Exit();
                var _ = StartQueueIfNecessaryAsync();
                await tcs.Task;
            }
        }

        public override void Resume()
        {
            base.Resume();
            var _ = StartQueueIfNecessaryAsync();
        }

        public override async Task FireAsync<TArgument>(ParameterizedTrigger<TTrigger, TArgument> parameterizedTrigger,
            TArgument argument)
        {
            if (!IsEnabled)
                return;

            var flag = true;

            queueMonitor.Enter();
            if (monitor.TryEnter())
            {
                asyncMonitor.Value = true;

                // Try to execute inline if the process queue is empty.
                if (queueCount == 0)
                {
                    queueMonitor.Exit();
                    flag = false;

                    try
                    {
                        await base.FireAsync(parameterizedTrigger, argument);
                    }
                    finally
                    {
                        queueMonitor.Enter();
                        if (queueCount > 0)
                        {
                            queueMonitor.Exit();
                            var _ = StartQueueIfNecessaryAsync(true);
                            // Should not exit monitor here. Its handled by the process queue.
                        }
                        else
                        {
                            queueMonitor.Exit();
                            monitor.Exit();
                            asyncMonitor.Value = false;
                        }
                    }
                }
            }

            if (flag)
            {
                // Fast path was not taken. Queue up the delgates.

                var tcs = new TaskCompletionSource<bool>();
                actionsQueue = actionsQueue.Enqueue(async () =>
                {
                    try
                    {
                        await base.FireAsync(parameterizedTrigger, argument);
                        tcs.TrySetResult(true);
                    }
                    catch (Exception ex)
                    {
                        tcs.TrySetException(ex);
                    }
                });
                queueCount++;
                queueMonitor.Exit();
                var _ = StartQueueIfNecessaryAsync();
                await tcs.Task;
            }
        }

        public override async Task FireAsync(TTrigger trigger)
        {
            if (!IsEnabled)
                return;

            var flag = true;

            queueMonitor.Enter();
            if (monitor.TryEnter())
            {
                asyncMonitor.Value = true;

                // Try to execute inline if the process queue is empty.
                if (queueCount == 0)
                {
                    queueMonitor.Exit();
                    flag = false;

                    try
                    {
                        await base.FireAsync(trigger);
                    }
                    finally
                    {
                        queueMonitor.Enter();
                        if (queueCount > 0)
                        {
                            queueMonitor.Exit();
                            var _ = StartQueueIfNecessaryAsync(true);
                            // Should not exit monitor here. Its handled by the process queue.
                        }
                        else
                        {
                            queueMonitor.Exit();
                            monitor.Exit();
                            asyncMonitor.Value = false;
                        }
                    }
                }
            }


            if (flag)
            {
                // Fast path was not taken. Queue up the delgates.

                var tcs = new TaskCompletionSource<bool>();
                actionsQueue = actionsQueue.Enqueue(async () =>
                {
                    try
                    {
                        await base.FireAsync(trigger);
                        tcs.TrySetResult(true);
                    }
                    catch (Exception ex)
                    {
                        tcs.TrySetException(ex);
                    }
                });
                queueCount++;
                queueMonitor.Exit();
                var _ = StartQueueIfNecessaryAsync();
                await tcs.Task;
            }
        }

        public void SkipPending()
        {
            queueMonitor.Enter();
            actionsQueue = ImmutableQueue<Func<Task>>.Empty;
            queueCount = 0;
            queueMonitor.Exit();
        }

        private Task StartQueueIfNecessaryAsync(bool lockTaken = false)
        {
            if (lockTaken || asyncMonitor.Value || monitor.TryEnter())
            {
                return ProcessQueueInternal();
            }

            return TaskHelpers.CompletedTask;
        }

        private async Task ProcessQueueInternal()
        {
            // Always yield if the task was queued.
            await Task.Yield();

            queueMonitor.Enter();
            try
            {
                while (queueCount > 0)
                {
                    var current = actionsQueue.Peek();
                    actionsQueue = actionsQueue.Dequeue();
                    queueCount--;
                    queueMonitor.Exit();

                    try
                    {
                        if (current != null)
                            await current();
                    }
                    finally
                    {
                        queueMonitor.Enter();
                    }
                }
            }
            finally
            {
                // Exit monitor regardless of this method entering the monitor.
                monitor.Exit();
                queueMonitor.Exit();
            }
        }
    }

    public sealed class NestedQueuedAwaitableStateMachineBase<TState, TTrigger> :
        NestedQueuedAwaitableStateMachineBase_<TState, TTrigger>
    {
        public NestedQueuedAwaitableStateMachineBase(TState initialState,
            AwaitableConfiguration<TState, TTrigger> awaitableConfiguration)
            : base(initialState, awaitableConfiguration)
        {
        }
    }
}
'''

**Comment by prasannavl** [comment]
Hello @oysteinkrog, 

Okay, there's both good news and bad news.. 

But before that, let me quickly rule out the problem with the above `AsyncLocal` scenario. It will break the machine's state coherency. In the example you gave above, the end state will not be StateC as you'd expect, but it'll be StateB. 

This is because, the machine pre-determines the set of actions to be executed for each state transition. Now, your transition will have to StateB (but now, only if it is valid at the point of validity checks - the current state of the machine is still one state behind. However, let's say I can easily fix this by just changing the order of the execution (though now it breaks the semantics, as OnEntry is supposed be its entering.. But not quite done yet. Machine successfully enters the state when its OnEntry doesn't throw and is successful) So, the question is, should I? Its a deep dark work once you enter the nested state transition world in this manner, without sacrificing on performance).  

It was a conscious decision I made to favor performance when I built it. I would however be open to re-design if people do see it being used heavily. 

Now to the problem, 

Lets approach this problem from a semantic perspective. 

So, lets say `StateA` triggers `StateB` inside its `Entry`. Now I end up with many hidden problems that the state machine cannot actually solve on its own. Why? When `StateA` triggers `StateB`, the state of the machine is in transition. 

Now the machine has already determined a bunch of actions to be done, its trigger functions if any, exit of the past state and so on. 

Now, if I do a nested transition. Which exit do I do first? Or complete take a different approach and do I exit twice?

These are all valid options in different scenarios which you may or may not desire. There are also more subtleties when you think about it how it all integrates together. 

Now, by no means is it impossible to make these choice above. But the problem is, what right for one will be wrong for the other. There's no way to come up with one optimal solution. 

So, this is a necessary limitation to completely avoid doing this. However, I should update the docs on semantics of each machine, and state that this is a deliberate choice. I tried thinking of throwing exception in certain scenarios, but I couldn't come up with a clear way to detect if it is indeed the right scenario. I'll try to update the docs this weekend. I think I it would be fair to call this behavior being undocumented as a bug.

Okay, so that was the bad news.. Now, to the good one,  

There's nothing stopping you from doing these. The way I do it is this. I simply do not call `await`. This way the action gets queued, and everything's stays sane and simple to reason with. I'd suggest that approach of thinking for scenarios where you cannot avoid it. 

But there will scenarios where you'll want to entire set to complete and respect the awaitable context. That is completely lacking at this point. I see a potential solution to be to work a context into the machine where these tasks can be attached to,  so that you're await while firing a machine includes these tasks as a single unit of transition. 

I've been want to bring contexts into the machine for a while, but unfortunately didn't get the time to do it yet. :( 

Or an alternate way to solve the problem would be have a machine execution core that simply attaches creates a `TaskCompleteSource` for each transition. So, now dispatches of async completion could happen with an internal response to the state change events. But this means, you're going to have to create TaskCompleteSource every time (currently, the machine tries to take a fast path when there is no concurrency issue, and `tcs` is only created when required if it cannot.

Anyway, I don't see an easy way for you to exactly what you want out of the box. I hope this gives a good insight into the problems.

**Comment by oysteinkrog** [comment]
Thank you so much for the great explanation, I understand now why this is a tricky problem :)
What I was trying to do is have the state machine represent the "interval"/transition state.
E.g. if the state machine represents a connection to a device, I would have both an "opening" and an "open" state.
Now I think I think that maybe the easiest way to do this is to it separate from the statemachine :)
