### ISSUE TITLE
Obtaining the trigger for any state change

### ISSUE THREAD

**Issue by omora-RA** [prasannavl/LiquidState#9]
Hello Prasanna,

First of all thanks for all the work you put into this project. I was evaluating Stateless, but these days async/await is a must.

My requirement is to run some logic when any State changes. That logic has to be aware of the Trigger that originated the change.

Stateless provides a method that suits my needs:
`public void OnTransitioned(Action<StateMachine<TState, TTrigger>.Transition> onTransitionAction)`

The Transition instance contains the previous and new State, and the origination Trigger

I guess the equivalent in your implementation is
`event Action<TState, TState> StateChanged`.

However, in your event handler there's no way to know which Trigger caused the State Change. Is there a way to obtain it?

If not, I could submit a PR, adding something in the lines of:
`public Task OnTransitionedAsync(Func<StateMachine<TState, TTrigger>.Transition,Task> onTransitionAction)`

Any thoughts?

**Comment by prasannavl** [comment]
Hi, 

You are correct that it currently doesn't provide an option to get the Trigger at this moment. I had thought about this, but since the existing API provided `StateChanged`, I couldn't incorporate it directly into it, since there is a semantic dilemma in case of re-entry without changing the states. 

And I didn't want two different events firing as well. But changing this would end up in a breaking change. So, I decided to leave it as it for now, since a new version with dynamic states should be out soon. Hopefully, this weekend, which should have this feature incorporated. :) 

And I appreciate for the offer for PR. Thanks! If you can wait till the weekend, you can pick it up from NuGet. For immediate usage, I guess you'll have to stick to custom builds till then.

**Comment by omora-RA** [comment]
Thanks for the update. No problem I'll wait for your next release. I see your point of not returning a Task. It makes sense.
Just one suggestion: You might want to encapsulate the previous/current states and the trigger in a `Transition<TState,TTrigger>` object (Stateless does it that way), then your event would be:
`event Action<Transition<TState, TTrigger>> TransitionExecuted`
That way you could extend the Transition in the future if needed.

**Comment by prasannavl** [comment]
Actually, it is. Just haven't finalized it, so noted a rough implementation without bringing a new abstraction name in, while not finialized :) .. There are actually more subtle implications without abstracting it, like the return value of TTrigger when `MoveToState` is used. (Eg: `default(TTrigger)` may not always be desirable when its a value type).

**Comment by omora-RA** [comment]
Good point... A Transition might not have an associated Trigger. Maybe adding a parameter `Transition.HasTrigger`

**Comment by prasannavl** [comment]
Mostly complete as of https://github.com/prasannavl/LiquidState/commit/ebdf2aa58516ccf6985ce22397b05f96c0ef39f0. But migration still pending for Awaitable machines.

**Comment by prasannavl** [comment]
Finished with https://github.com/prasannavl/LiquidState/commit/e651b8aac4eea29f869c0601c10c69c5602f2e75
